using System.IO;
using System.Linq;
using com.vrcfury.api;
using UnityEditor;
using UnityEngine;
using PackageInfo = UnityEditor.PackageManager.PackageInfo;
using com.vrcfury.api.Components;

namespace Wholesome
{
    public class SFX
    {
        private const string SourcePackage = "wholesomevr.sps-configurator";
        private const string SourcePath = "Packages/" + SourcePackage + "/Assets/SFX/";
        private const string DestinationPath = "Assets/!Wholesome/SPS Configurator/";

        private static string GetPackageVersion()
        {
            var packageInfo = PackageInfo.FindForAssetPath("Packages/" + SourcePackage);
            return packageInfo.version;
        }

        private static string CopyAssets()
        {
            string packageVersion = GetPackageVersion();
            string fullDestPath = DestinationPath + packageVersion + "/SFX/";
            var assetPaths = AssetDatabase.FindAssets("", new[] { SourcePath })
                .Select(AssetDatabase.GUIDToAssetPath).ToArray();
            var prefabPath = Path.Join(fullDestPath, "SFX.prefab");

            var prefabExists = File.Exists(prefabPath);

            foreach (var path in assetPaths)
            {
                string relativePath = path.Substring(SourcePath.Length);
                string destFilePath = fullDestPath + relativePath;
                if (!File.Exists(destFilePath))
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(destFilePath));
                    AssetDatabase.CopyAsset(path, destFilePath);
                }
            }
            var prefab = PrefabUtility.LoadPrefabContents(prefabPath);

            // Prefab was newly created, need to add Full Controller and change audio clips
            if (!prefabExists)
            {
                var fx = AssetDatabase.LoadAllAssetsAtPath(Path.Join(fullDestPath, "AAC_SFX.controller"))
                    .FirstOrDefault(a => a.name == "zAutogenerated__WH__SFX_107040187");
                var ctr = FuryComponents.CreateFullController(prefab);
                ctr.AddController(fx as RuntimeAnimatorController);
                ctr.AddGlobalParam("WH_SFX_Depth");
                ctr.AddGlobalParam("WH_SFX_On");

                foreach (var audioSource in prefab.GetComponentsInChildren<AudioSource>(true))
                {
                    var clipPath = AssetDatabase.GetAssetPath(audioSource.clip);
                    var newClipPath = fullDestPath + clipPath.Substring(SourcePath.Length);
                    audioSource.clip = AssetDatabase.LoadAssetAtPath<AudioClip>(newClipPath);
                }
                PrefabUtility.SaveAsPrefabAsset(prefab, prefabPath);
                PrefabUtility.UnloadPrefabContents(prefab);
            }
            AssetDatabase.Refresh();
            return prefabPath;
        }

        public static void Apply(GameObject gameObject, FurySocket socket)
        {
            var path = CopyAssets();
            var sfxPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            var sfxObject = (GameObject)PrefabUtility.InstantiatePrefab(sfxPrefab, gameObject.transform);

            socket.AddDepthActions(new Vector2(-.5f, 0), 0, true)
                .AddAap("WH_SFX_Depth", 1);
            socket.GetActiveActions()
                .AddTurnOn(sfxObject);
        }

        public static void AddToggle(GameObject spsObject)
        {
            var toggle = FuryComponents.CreateToggle(spsObject);
            toggle.SetMenuPath("SPS/Options/Sound FX");
            toggle.SetGlobalParameter("WH_SFX_On");
            toggle.SetSaved();
            toggle.SetDefaultOn();
        }
    }
}