name: Build Repo Listing

env:
  CurrentPackageName: wholesomevr.sps-configurator
  listPublishDirectory: Website
  pathToCi: ci
  
on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build Release]
    types:
      - completed
  release:
     types: [published, created, edited, unpublished, deleted, released]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3 # check out this repo
      - uses: actions/checkout@v3 # check out automation repo
        with:
          repository: wholesomevr/package-list-action
          path: ${{env.pathToCi}}
          clean: false # otherwise the local repo will no longer be checked out
          
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{env.pathToCi}}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - id: vrcf
        run: |
          release_url=$(gh release view --json assets -q .assets.[0].url -R VRCFury/VRCFury)
          echo "RELEASE_URL=$release_url" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Build Package Version Listing
        run: ${{env.pathToCi}}/build.cmd BuildRepoListing --root ${{env.pathToCi}} --list-publish-directory $GITHUB_WORKSPACE/${{env.listPublishDirectory}} --current-package-name ${{env.CurrentPackageName}} --add-package-id com.vrcfury.vrcfury --add package-url $VRCFURY_URL 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VRCFURY_URL: ${{ steps.vrcf.outputs.RELEASE_URL }}
 
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{env.listPublishDirectory}}
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
